name: 🔄 Format & Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🛠️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: 🔧 Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🔄 Format and build
        run: |
          npm run format
          npm run build

      - name: 💾 Commit changes
        run: |
          git add .
          git commit -m "chore: format and build"
          git push
